### PR TITLE
Escape utme values `'`, `)`, and `*`

### PR DESCRIPTION
**Pull request by smerchek**
`'` => `'0`
`)` => `'1`
`*` => `'2`

Reference: [StackOverflow: Passing special values to google analytics](http://stackoverflow.com/questions/7948214/passing-special-values-to-google-analytics)

### CODE REVIEW

**Comment by dustyburwell** [comment]
LGTM :+1:

**Comment by dustyburwell** [comment]
Unfortunately, without a Windows machine handy, I can't publish a new NuGet for this at the moment. I'll add you as an owner on the NuGet package if you want to publish a new version. What's your NuGet user name?

**Comment by smerchek** [comment]
it is `smerchek`

Is there anything special I need to do to build the nupkg for this project?
- Scott

**Comment by dustyburwell** [comment]
Okay, it says "pending approval". I'm not 100% on what that means, but I assume you'll have access soon. It's been a year since I've published a NuGet package, but I think you just have to bump the assembly version, run a build, and run `nuget pack`, then `nuget publish`. I believe this project uses the csproj file instead of a nuget package definition file.

**Comment by smerchek** [comment]
Ok, didn't realize I could just pack the csproj. Ready for a stable release of 2.0.0 then? (it's still prerelease at the moment)

**Comment by dustyburwell** [comment]
Yes, 2.0.0 is fine assuming it's good enough for you all.

**Pull request merged**
